Removed unnecessary print statements
DovaX/dbhydra pull request #63
Opened 2023-10-27 20:24 UTC by ZaiZu2

2023-10-27 21:11 UTC, Omastto1 requested changes
add verbose argument instead of removing them

2023-10-27 21:17 UTC, DovaX requested changes

2023-10-27 21:17 UTC, DovaX commented on dbhydra/dbhydra_core.py
> +        pass
better full remove than replace for pass - or why is it done like that?

2023-10-27 21:17 UTC, DovaX commented on dbhydra/dbhydra_core.py
> +        pass
It's quite handy to see queries in the console btw - most of the time this is beneficial

2023-11-04 16:42 UTC, DovaX commented
I am doing major refactor - some of the prints/logs are important, I close this PR for now

2023-11-04 16:42 UTC, closed without merging