Daniel --> master
DovaX/dbhydra pull request #66
Opened 2024-01-13 17:49 UTC by YoungMasterGandalf

This PR introduces 2 hotfixes:
* `Table` class init
* `AbstractTable` class init

Both needed for proper functionality (fix crashes). However a deeper thought about the implementation is probably needed (they are just hotfixes after all).

2024-01-19 13:32 UTC, DovaX requested changes

2024-01-19 13:32 UTC, DovaX commented on dbhydra/src/abstract_table.py
> +                self.columns[i] = column[0] if type(column) == list else column
I dont like this, why should the information be truncated? When can this even happen that column from columns would contain a list inside?

2024-01-19 13:32 UTC, DovaX commented on dbhydra/src/tables.py
> +        self.types = types
Deprecation warning shouldnt be removed

2024-01-19 13:32 UTC, DovaX commented on dbhydra/src/tables.py
> +        self.types = types
shouldnt super.__init__ include also "types"?

2024-01-22 00:06 UTC, merged

2024-01-22 00:07 UTC, DovaX commented
I merged it but it shouldnt remain in the code for long time @YoungMasterGandalf

2024-01-22 00:07 UTC, DovaX commented
Please prepare fix PR

2024-01-22 10:48 UTC, YoungMasterGandalf commented
@DovaX Yes, I will it ASAP